DROP TABLE IF EXISTS ingredients;

CREATE TABLE ingredients (  
   id INT NOT NULL AUTO_INCREMENT,
   ingredient TEXT NOT NULL AUTO_INCREMENT,  
   expiry TEXT NOT NULL AUTO_INCREMENT,  
   amount INT NOT NULL AUTO_INCREMENT,
   PRIMARY KEY ( id )  
);